
services:
  mongodb:
    image: mongo:7.0
    container_name: optica-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: optica_historial
    volumes:
      - mongo_data:/data/db
    networks:
      - optica-network

  # Interfaz Web para administrar MongoDB de forma visual (http://localhost:8081)
  mongo-express:
    image: mongo-express:latest
    container_name: optica-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb
    networks:
      - optica-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - optica-network

  redis:
    image: redis:7.2-alpine
    container_name: optica-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - optica-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - optica-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongo_data:
  redis_data:

networks:
  optica-network:
    driver: bridge