server:
  port: 8084

spring:
  application:
    name: servicio-pacientes
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017}/optica_pacientes
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: patient-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enabled: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      auto-startup: false

logging:
  level:
    edu.uptc.swii: DEBUG