# Configuración del Servidor
spring.application.name=servicio-auth
server.port=8081

# Configuración de MySQL apuntando a la BD unificada 'optica'
spring.datasource.url=jdbc:mysql://localhost:3306/optica?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración básica del consumidor
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=auth-group
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializadores con manejo de errores
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Paquetes de confianza (Le dice a Jackson que confíe en cualquier clase o paquete destino)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Forzar el mapeo del alias al evento local de Auth
# Usa los encabezados de tipo si están, pero si fallan, confía en el parámetro del método
##spring.kafka.consumer.properties.spring.json.type.mapping=edu.uptc.swii.servicio_usuarios.domain.events.UsuarioCreatedEvent:edu.uptc.swii.servicio_auth.infrastructure.messaging.UsuarioCreatedEvent,edu.uptc.swii.servicio_usuarios.domain.events.UsuarioRolUpdatedEvent:edu.uptc.swii.servicio_auth.domain.events.UsuarioRolUpdatedEvent
spring.kafka.consumer.properties.spring.json.type.mapping=usuario_creado:edu.uptc.swii.servicio_auth.infrastructure.messaging.UsuarioCreatedEvent,edu.uptc.swii.servicio_usuarios.domain.events.UsuarioRolUpdatedEvent:edu.uptc.swii.servicio_auth.domain.events.UsuarioRolUpdatedEvent
##spring.kafka.consumer.properties.spring.json.type.mapping=edu.uptc.swii.servicio_usuarios.domain.events.UsuarioCreatedEvent:edu.uptc.swii.servicio_auth.domain.events.UsuarioCreatedEvent,edu.uptc.swii.servicio_usuarios.domain.events.UsuarioRolUpdatedEvent:edu.uptc.swii.servicio_auth.domain.events.UsuarioRolUpdatedEvent
## spring.kafka.consumer.properties.spring.json.type.mapping=usuario_creado:edu.uptc.swii.servicio_auth.infrastructure.messaging.UsuarioCreatedEvent